# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22fc4892fad6c242f826cdc79337add8d9d8b2ca87ade451b478d203d727fdd51b0b12ac10864832aa726b87b307ce1a6f3b0cb98167e77cf13a30ec186b9277

test:
  secret_key_base: 9ab1d224398e99eb6a00e659920e7b12b11b0c3c4b991d6ebf25c13bae289780c53b594e5c62cbbf5081108561de9b1a5062e658cef50d9346376fedb6cae5c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
